In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/players.csv")
df.shape

(17954, 51)

In [2]:
df.head()

,name,full_name,birth_date,age,height_cm,weight_kgs,positions,nationality,overall_rating,potential,...,long_shots,aggression,interceptions,positioning,vision,penalties,composure,marking,standing_tackle,sliding_tackle
0,L. Messi,Lionel Andrés Messi Cuccittini,6/24/1987,31,170.18,72.1,"CF,RW,ST",Argentina,94,94,...,94,48,22,94,94,75,96,33,28,26
1,C. Eriksen,Christian Dannemann Eriksen,2/14/1992,27,154.94,76.2,"CAM,RM,CM",Denmark,88,89,...,89,46,56,84,91,67,88,59,57,22
2,P. Pogba,Paul Pogba,3/15/1993,25,190.50,83.9,"CM,CAM",France,88,91,...,82,78,64,82,88,82,87,63,67,67
3,L. Insigne,Lorenzo Insigne,6/4/1991,27,162.56,59.0,"LW,ST",Italy,88,88,...,84,34,26,83,87,61,83,51,24,22
4,K. Koulibaly,Kalidou Koulibaly,6/20/1991,27,187.96,88.9,CB,Senegal,88,91,...,15,87,88,24,49,33,80,91,88,87

In [3]:
df.info

<bound method DataFrame.info of                  name                         full_name birth_date  age  \
0            L. Messi    Lionel Andrés Messi Cuccittini  6/24/1987   31
1          C. Eriksen      Christian  Dannemann Eriksen  2/14/1992   27
2            P. Pogba                        Paul Pogba  3/15/1993   25
3          L. Insigne                   Lorenzo Insigne   6/4/1991   27
4        K. Koulibaly                 Kalidou Koulibaly  6/20/1991   27
...               ...                               ...        ...  ...
17949     R. McKenzie                    Rory  McKenzie  10/7/1993   25
17950       M. Sipľak                     Michal Sipľak   2/2/1996   23
17951      J. Bekkema                       Jan Bekkema   4/9/1996   22
17952      A. Al Yami               Abdulrahman Al Yami  6/19/1997   21
17953  Júnior Brumado  José Francisco dos Santos Júnior  5/15/1999   19

       height_cm  weight_kgs  positions   nationality  overall_rating  \
0         170.18        72.1   CF,RW,ST     Argentina              94
1         154.94        76.2  CAM,RM,CM       Denmark              88
2         190.50        83.9     CM,CAM        France              88
3         162.56        59.0      LW,ST         Italy              88
4         187.96        88.9         CB       Senegal              88
...          ...         ...        ...           ...             ...
17949     175.26        74.8  RM,CAM,CM      Scotland              67
17950     182.88        79.8         LB      Slovakia              59
17951     185.42        89.8         GK   Netherlands              59
17952     175.26        64.9      ST,LM  Saudi Arabia              59
17953     190.50        79.8         ST        Brazil              59

       potential  ...  long_shots  aggression interceptions  positioning  \
0             94  ...          94          48            22           94
1             89  ...          89          46            56           84
2             91  ...          82          78            64           82
3             88  ...          84          34            26           83
4             91  ...          15          87            88           24
...          ...  ...         ...         ...           ...          ...
17949         70  ...          54          69            41           60
17950         67  ...          22          62            55           42
17951         67  ...           9          27            10            5
17952         71  ...          58          38            15           54
17953         75  ...          53          67            20           53

       vision  penalties composure  marking standing_tackle  sliding_tackle
0          94         75        96       33              28              26
1          91         67        88       59              57              22
2          88         82        87       63              67              67
3          87         61        83       51              24              22
4          49         33        80       91              88              87
...       ...        ...       ...      ...             ...             ...
17949      64         63        56       40              20              18
17950      39         32        52       53              64              60
17951      25         16        47        9              12              13
17952      52         50        53       16              18              17
17953      49         52        45       23              31              21

[17954 rows x 51 columns]>

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,17954.0,2.556545e+01,4.705708e+00,17.0,22.00,25.00,29.00,4.600000e+01
height_cm,17954.0,1.749469e+02,1.402945e+01,152.4,154.94,175.26,185.42,2.057400e+02
weight_kgs,17954.0,7.530105e+01,7.083684e+00,49.9,69.90,74.80,79.80,1.102000e+02
overall_rating,17954.0,6.624017e+01,6.963730e+00,47.0,62.00,66.00,71.00,9.400000e+01
potential,17954.0,7.143093e+01,6.131339e+00,48.0,67.00,71.00,75.00,9.500000e+01
value_euro,17699.0,2.479280e+06,5.687014e+06,10000.0,325000.00,700000.00,2100000.00,1.105000e+08
wage_euro,17708.0,9.902135e+03,2.199559e+04,1000.0,1000.00,3000.00,9000.00,5.650000e+05
international_reputation(1-5),17954.0,1.111674e+00,3.921679e-01,1.0,1.00,1.00,1.00,5.000000e+00
weak_foot(1-5),17954.0,2.945695e+00,6.636915e-01,1.0,3.00,3.00,3.00,5.000000e+00
skill_moves(1-5),17954.0,2.361034e+00,7.632226e-01,1.0,2.00,2.00,3.00,5.000000e+00
release_clause_euro,16117.0,4.622522e+06,1.129077e+07,13000.0,525000.00,1200000.00,3500000.00,2.265000e+08
national_rating,857.0,7.634189e+01,4.786667e+00,63.0,73.00,75.00,81.00,8.500000e+01
national_jersey_number,857.0,1.245624e+01,8.098157e+00,1.0,6.00,12.00,18.00,9.900000e+01
crossing,17954.0,4.969767e+01,1.848331e+01,5.0,38.00,54.00,64.00,9.300000e+01
finishing,17954.0,4.535825e+01,1.964079e+01,2.0,30.00,49.00,62.00,9.500000e+01
heading_accuracy,17954.0,5.214821e+01,1.752182e+01,4.0,44.00,56.00,64.00,9.400000e+01
short_passing,17954.0,5.856606e+01,1.486318e+01,7.0,53.00,62.00,68.00,9.300000e+01
volleys,17954.0,4.275521e+01,1.780294e+01,3.0,30.00,44.00,57.00,9.000000e+01
dribbling,17954.0,5.527899e+01,1.909188e+01,4.0,49.00,61.00,68.00,9.700000e+01
curve,17954.0,4.710115e+01,1.853662e+01,6.0,34.00,49.00,62.00,9.400000e+01
freekick_accuracy,17954.0,4.268809e+01,1.756563e+01,3.0,30.00,41.00,56.00,9.400000e+01
long_passing,17954.0,5.266743e+01,1.542155e+01,9.0,43.00,56.00,64.00,9.300000e+01
ball_control,17954.0,5.822391e+01,1.687572e+01,5.0,54.00,63.00,69.00,9.600000e+01
acceleration,17954.0,6.469622e+01,1.500134e+01,12.0,57.00,67.00,75.00,9.700000e+01
sprint_speed,17954.0,6.480350e+01,1.472275e+01,12.0,58.00,67.00,75.00,9.600000e+01
agility,17954.0,6.337746e+01,1.480695e+01,11.0,55.00,66.00,74.00,9.600000e+01
reactions,17954.0,6.182188e+01,9.075675e+00,24.0,56.00,62.00,68.00,9.600000e+01
balance,17954.0,6.387006e+01,1.417404e+01,16.0,56.00,66.00,74.00,9.600000e+01
shot_power,17954.0,5.531987e+01,1.735130e+01,2.0,45.00,59.00,68.00,9.500000e+01
jumping,17954.0,6.495522e+01,1.170571e+01,15.0,58.00,66.00,73.00,9.500000e+01
stamina,17954.0,6.313384e+01,1.591755e+01,12.0,56.00,66.00,74.00,9.700000e+01
strength,17954.0,6.515885e+01,1.253595e+01,20.0,58.00,66.00,74.00,9.700000e+01
long_shots,17954.0,4.685246e+01,1.942934e+01,3.0,32.00,51.00,62.00,9.400000e+01
aggression,17954.0,5.581653e+01,1.739405e+01,11.0,44.00,59.00,69.00,9.500000e+01
interceptions,17954.0,4.665796e+01,2.075465e+01,3.0,26.00,52.00,64.00,9.200000e+01
positioning,17954.0,4.985730e+01,1.969431e+01,2.0,38.00,55.00,64.00,9.500000e+01
vision,17954.0,5.340626e+01,1.415604e+01,10.0,44.00,55.00,64.00,9.400000e+01
penalties,17954.0,4.835730e+01,1.581084e+01,5.0,38.00,49.00,60.00,9.200000e+01
composure,17954.0,5.868018e+01,1.162554e+01,12.0,51.00,60.00,67.00,9.600000e+01
marking,17954.0,4.716286e+01,2.003735e+01,3.0,30.00,52.50,64.00,9.400000e+01
standing_tackle,17954.0,4.773304e+01,2.167497e+01,2.0,27.00,55.00,66.00,9.300000e+01
sliding_tackle,17954.0,4.570592e+01,2.128581e+01,3.0,24.00,52.00,64.00,9.000000e+01

In [5]:
df["overall_rating"].describe()

count    17954.000000
mean        66.240169
std          6.963730
min         47.000000
25%         62.000000
50%         66.000000
75%         71.000000
max         94.000000
Name: overall_rating, dtype: float64